### PR TITLE
Update main_out.js

### PR DESCRIPTION
**Pull request by Gimmo**
I made alot of cosmetical changes and remove some memory leakage sources. Main logic have no any changes.

### CODE REVIEW

**Comment by HAlexTM** [comment]
Awesome work, can you please post some screenshot describing the main changes, thank you :)

**Comment by HAlexTM** [comment]
Can you please explain better what you did?

**Comment by Gimmo** [comment]
Set semicolons, where needed.
Set strong comparison, where posiible.
Define undefined variables.
Repair variables suspicious to be out of scope. 
Remove function definition inside the loop to upper level. (in movePoints:)

Nothing more.

**Comment by MastaCoder** [comment]
You forgot to write the new code over the old code that you edited, you inserted the new code right into the old code and that breaks everything 🗡

**Pull request closed without merging**
