### PR TITLE
Little performance boosts & get that vanilla feel

### PR DESCRIPTION
**Pull request by Luka967**
I think it's actually worse in performance than before, but it's got the agar-like rendering now. Tried implementing food detection but with no luck, will try again later.
Has text stroking with minimal edits. One line edit to be precise.

### CODE REVIEW

**Comment by HAlexTM** [comment]
onpaste 20161218-214208

**Comment by Luka967** [comment]
I've seen this while playtesting and have no idea why it's happening. I'll see some more if I can fix this.

**Comment by HAlexTM** [comment]
The text is really good, I'm checking for performance issues
onpaste 20161218-214646

**Comment by Luka967** [comment]
Fixed the mass problem

**Comment by MastaCoder** [comment]
That name render didn't affect performance? Impressive!

@Luka967 Want to become a contributor to this? I've seen a lot of your work on Ogar and they're impressive 👍

**Comment by Luka967** [comment]
@MastaCoder Would be appreciated :)

**Pull request merged**
